# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.21.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.21.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alex/gitarea/playground/space-invaders-game-assignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.21.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.21.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build/CMakeFiles /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build/SpaceInvaders/code//CMakeFiles/progress.marks
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders/code/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders/code/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders/code/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders/code/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/rule:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/rule
.PHONY : SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/rule

# Convenience name for target.
space-invaders-game-assignment: SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/rule
.PHONY : space-invaders-game-assignment

# fast build rule for target.
space-invaders-game-assignment/fast:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build
.PHONY : space-invaders-game-assignment/fast

source/Basic/string.o: source/Basic/string.cpp.o
.PHONY : source/Basic/string.o

# target to build an object file
source/Basic/string.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Basic/string.cpp.o
.PHONY : source/Basic/string.cpp.o

source/Basic/string.i: source/Basic/string.cpp.i
.PHONY : source/Basic/string.i

# target to preprocess a source file
source/Basic/string.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Basic/string.cpp.i
.PHONY : source/Basic/string.cpp.i

source/Basic/string.s: source/Basic/string.cpp.s
.PHONY : source/Basic/string.s

# target to generate assembly for a file
source/Basic/string.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Basic/string.cpp.s
.PHONY : source/Basic/string.cpp.s

source/Graphics/SpriteRenderer.o: source/Graphics/SpriteRenderer.cpp.o
.PHONY : source/Graphics/SpriteRenderer.o

# target to build an object file
source/Graphics/SpriteRenderer.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Graphics/SpriteRenderer.cpp.o
.PHONY : source/Graphics/SpriteRenderer.cpp.o

source/Graphics/SpriteRenderer.i: source/Graphics/SpriteRenderer.cpp.i
.PHONY : source/Graphics/SpriteRenderer.i

# target to preprocess a source file
source/Graphics/SpriteRenderer.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Graphics/SpriteRenderer.cpp.i
.PHONY : source/Graphics/SpriteRenderer.cpp.i

source/Graphics/SpriteRenderer.s: source/Graphics/SpriteRenderer.cpp.s
.PHONY : source/Graphics/SpriteRenderer.s

# target to generate assembly for a file
source/Graphics/SpriteRenderer.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Graphics/SpriteRenderer.cpp.s
.PHONY : source/Graphics/SpriteRenderer.cpp.s

source/Graphics/TextRenderer.o: source/Graphics/TextRenderer.cpp.o
.PHONY : source/Graphics/TextRenderer.o

# target to build an object file
source/Graphics/TextRenderer.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Graphics/TextRenderer.cpp.o
.PHONY : source/Graphics/TextRenderer.cpp.o

source/Graphics/TextRenderer.i: source/Graphics/TextRenderer.cpp.i
.PHONY : source/Graphics/TextRenderer.i

# target to preprocess a source file
source/Graphics/TextRenderer.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Graphics/TextRenderer.cpp.i
.PHONY : source/Graphics/TextRenderer.cpp.i

source/Graphics/TextRenderer.s: source/Graphics/TextRenderer.cpp.s
.PHONY : source/Graphics/TextRenderer.s

# target to generate assembly for a file
source/Graphics/TextRenderer.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Graphics/TextRenderer.cpp.s
.PHONY : source/Graphics/TextRenderer.cpp.s

source/Math/Vec2f.o: source/Math/Vec2f.cpp.o
.PHONY : source/Math/Vec2f.o

# target to build an object file
source/Math/Vec2f.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Math/Vec2f.cpp.o
.PHONY : source/Math/Vec2f.cpp.o

source/Math/Vec2f.i: source/Math/Vec2f.cpp.i
.PHONY : source/Math/Vec2f.i

# target to preprocess a source file
source/Math/Vec2f.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Math/Vec2f.cpp.i
.PHONY : source/Math/Vec2f.cpp.i

source/Math/Vec2f.s: source/Math/Vec2f.cpp.s
.PHONY : source/Math/Vec2f.s

# target to generate assembly for a file
source/Math/Vec2f.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Math/Vec2f.cpp.s
.PHONY : source/Math/Vec2f.cpp.s

source/Platform/Display.o: source/Platform/Display.cpp.o
.PHONY : source/Platform/Display.o

# target to build an object file
source/Platform/Display.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Platform/Display.cpp.o
.PHONY : source/Platform/Display.cpp.o

source/Platform/Display.i: source/Platform/Display.cpp.i
.PHONY : source/Platform/Display.i

# target to preprocess a source file
source/Platform/Display.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Platform/Display.cpp.i
.PHONY : source/Platform/Display.cpp.i

source/Platform/Display.s: source/Platform/Display.cpp.s
.PHONY : source/Platform/Display.s

# target to generate assembly for a file
source/Platform/Display.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Platform/Display.cpp.s
.PHONY : source/Platform/Display.cpp.s

source/Platform/Input.o: source/Platform/Input.cpp.o
.PHONY : source/Platform/Input.o

# target to build an object file
source/Platform/Input.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Platform/Input.cpp.o
.PHONY : source/Platform/Input.cpp.o

source/Platform/Input.i: source/Platform/Input.cpp.i
.PHONY : source/Platform/Input.i

# target to preprocess a source file
source/Platform/Input.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Platform/Input.cpp.i
.PHONY : source/Platform/Input.cpp.i

source/Platform/Input.s: source/Platform/Input.cpp.s
.PHONY : source/Platform/Input.s

# target to generate assembly for a file
source/Platform/Input.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Platform/Input.cpp.s
.PHONY : source/Platform/Input.cpp.s

source/SpaceInvaders.o: source/SpaceInvaders.cpp.o
.PHONY : source/SpaceInvaders.o

# target to build an object file
source/SpaceInvaders.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders.cpp.o
.PHONY : source/SpaceInvaders.cpp.o

source/SpaceInvaders.i: source/SpaceInvaders.cpp.i
.PHONY : source/SpaceInvaders.i

# target to preprocess a source file
source/SpaceInvaders.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders.cpp.i
.PHONY : source/SpaceInvaders.cpp.i

source/SpaceInvaders.s: source/SpaceInvaders.cpp.s
.PHONY : source/SpaceInvaders.s

# target to generate assembly for a file
source/SpaceInvaders.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders.cpp.s
.PHONY : source/SpaceInvaders.cpp.s

source/SpaceInvaders/Entities/Bomb/Bomb.o: source/SpaceInvaders/Entities/Bomb/Bomb.cpp.o
.PHONY : source/SpaceInvaders/Entities/Bomb/Bomb.o

# target to build an object file
source/SpaceInvaders/Entities/Bomb/Bomb.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Bomb/Bomb.cpp.o
.PHONY : source/SpaceInvaders/Entities/Bomb/Bomb.cpp.o

source/SpaceInvaders/Entities/Bomb/Bomb.i: source/SpaceInvaders/Entities/Bomb/Bomb.cpp.i
.PHONY : source/SpaceInvaders/Entities/Bomb/Bomb.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Bomb/Bomb.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Bomb/Bomb.cpp.i
.PHONY : source/SpaceInvaders/Entities/Bomb/Bomb.cpp.i

source/SpaceInvaders/Entities/Bomb/Bomb.s: source/SpaceInvaders/Entities/Bomb/Bomb.cpp.s
.PHONY : source/SpaceInvaders/Entities/Bomb/Bomb.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Bomb/Bomb.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Bomb/Bomb.cpp.s
.PHONY : source/SpaceInvaders/Entities/Bomb/Bomb.cpp.s

source/SpaceInvaders/Entities/Invader/Invader.o: source/SpaceInvaders/Entities/Invader/Invader.cpp.o
.PHONY : source/SpaceInvaders/Entities/Invader/Invader.o

# target to build an object file
source/SpaceInvaders/Entities/Invader/Invader.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/Invader.cpp.o
.PHONY : source/SpaceInvaders/Entities/Invader/Invader.cpp.o

source/SpaceInvaders/Entities/Invader/Invader.i: source/SpaceInvaders/Entities/Invader/Invader.cpp.i
.PHONY : source/SpaceInvaders/Entities/Invader/Invader.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Invader/Invader.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/Invader.cpp.i
.PHONY : source/SpaceInvaders/Entities/Invader/Invader.cpp.i

source/SpaceInvaders/Entities/Invader/Invader.s: source/SpaceInvaders/Entities/Invader/Invader.cpp.s
.PHONY : source/SpaceInvaders/Entities/Invader/Invader.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Invader/Invader.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/Invader.cpp.s
.PHONY : source/SpaceInvaders/Entities/Invader/Invader.cpp.s

source/SpaceInvaders/Entities/Invader/States/AliveState.o: source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Invader/States/AliveState.o

# target to build an object file
source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.o

source/SpaceInvaders/Entities/Invader/States/AliveState.i: source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Invader/States/AliveState.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.i

source/SpaceInvaders/Entities/Invader/States/AliveState.s: source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Invader/States/AliveState.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Invader/States/AliveState.cpp.s

source/SpaceInvaders/Entities/Invader/States/DeadState.o: source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Invader/States/DeadState.o

# target to build an object file
source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.o

source/SpaceInvaders/Entities/Invader/States/DeadState.i: source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Invader/States/DeadState.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.i

source/SpaceInvaders/Entities/Invader/States/DeadState.s: source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Invader/States/DeadState.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Invader/States/DeadState.cpp.s

source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.o: source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.o

# target to build an object file
source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.o

source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.i: source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.i

# target to preprocess a source file
source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.i

source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.s: source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.cpp.s

source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.o: source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.o

# target to build an object file
source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.o

source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.i: source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.i

# target to preprocess a source file
source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.i

source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.s: source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.cpp.s

source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.o: source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.o

# target to build an object file
source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.o

source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.i: source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.i

# target to preprocess a source file
source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.i

source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.s: source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.cpp.s

source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.o: source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.o

# target to build an object file
source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.o

source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.i: source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.i

# target to preprocess a source file
source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.i

source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.s: source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.cpp.s

source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.o: source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.o

# target to build an object file
source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.o
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.o

source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.i: source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.i

# target to preprocess a source file
source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.i
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.i

source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.s: source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.s
.PHONY : source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.cpp.s

source/SpaceInvaders/Entities/Rocket/Rocket.o: source/SpaceInvaders/Entities/Rocket/Rocket.cpp.o
.PHONY : source/SpaceInvaders/Entities/Rocket/Rocket.o

# target to build an object file
source/SpaceInvaders/Entities/Rocket/Rocket.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Rocket/Rocket.cpp.o
.PHONY : source/SpaceInvaders/Entities/Rocket/Rocket.cpp.o

source/SpaceInvaders/Entities/Rocket/Rocket.i: source/SpaceInvaders/Entities/Rocket/Rocket.cpp.i
.PHONY : source/SpaceInvaders/Entities/Rocket/Rocket.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Rocket/Rocket.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Rocket/Rocket.cpp.i
.PHONY : source/SpaceInvaders/Entities/Rocket/Rocket.cpp.i

source/SpaceInvaders/Entities/Rocket/Rocket.s: source/SpaceInvaders/Entities/Rocket/Rocket.cpp.s
.PHONY : source/SpaceInvaders/Entities/Rocket/Rocket.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Rocket/Rocket.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Rocket/Rocket.cpp.s
.PHONY : source/SpaceInvaders/Entities/Rocket/Rocket.cpp.s

source/SpaceInvaders/Entities/Ship/Ship.o: source/SpaceInvaders/Entities/Ship/Ship.cpp.o
.PHONY : source/SpaceInvaders/Entities/Ship/Ship.o

# target to build an object file
source/SpaceInvaders/Entities/Ship/Ship.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/Ship.cpp.o
.PHONY : source/SpaceInvaders/Entities/Ship/Ship.cpp.o

source/SpaceInvaders/Entities/Ship/Ship.i: source/SpaceInvaders/Entities/Ship/Ship.cpp.i
.PHONY : source/SpaceInvaders/Entities/Ship/Ship.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Ship/Ship.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/Ship.cpp.i
.PHONY : source/SpaceInvaders/Entities/Ship/Ship.cpp.i

source/SpaceInvaders/Entities/Ship/Ship.s: source/SpaceInvaders/Entities/Ship/Ship.cpp.s
.PHONY : source/SpaceInvaders/Entities/Ship/Ship.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Ship/Ship.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/Ship.cpp.s
.PHONY : source/SpaceInvaders/Entities/Ship/Ship.cpp.s

source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.o: source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.o

# target to build an object file
source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.o

source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.i: source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.i

source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.s: source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.cpp.s

source/SpaceInvaders/Entities/Ship/States/RechargingFireState.o: source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Ship/States/RechargingFireState.o

# target to build an object file
source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.o
.PHONY : source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.o

source/SpaceInvaders/Entities/Ship/States/RechargingFireState.i: source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Ship/States/RechargingFireState.i

# target to preprocess a source file
source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.i
.PHONY : source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.i

source/SpaceInvaders/Entities/Ship/States/RechargingFireState.s: source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Ship/States/RechargingFireState.s

# target to generate assembly for a file
source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.s
.PHONY : source/SpaceInvaders/Entities/Ship/States/RechargingFireState.cpp.s

source/SpaceInvaders/Game.o: source/SpaceInvaders/Game.cpp.o
.PHONY : source/SpaceInvaders/Game.o

# target to build an object file
source/SpaceInvaders/Game.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Game.cpp.o
.PHONY : source/SpaceInvaders/Game.cpp.o

source/SpaceInvaders/Game.i: source/SpaceInvaders/Game.cpp.i
.PHONY : source/SpaceInvaders/Game.i

# target to preprocess a source file
source/SpaceInvaders/Game.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Game.cpp.i
.PHONY : source/SpaceInvaders/Game.cpp.i

source/SpaceInvaders/Game.s: source/SpaceInvaders/Game.cpp.s
.PHONY : source/SpaceInvaders/Game.s

# target to generate assembly for a file
source/SpaceInvaders/Game.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Game.cpp.s
.PHONY : source/SpaceInvaders/Game.cpp.s

source/SpaceInvaders/Scenes/ActionPhase.o: source/SpaceInvaders/Scenes/ActionPhase.cpp.o
.PHONY : source/SpaceInvaders/Scenes/ActionPhase.o

# target to build an object file
source/SpaceInvaders/Scenes/ActionPhase.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/ActionPhase.cpp.o
.PHONY : source/SpaceInvaders/Scenes/ActionPhase.cpp.o

source/SpaceInvaders/Scenes/ActionPhase.i: source/SpaceInvaders/Scenes/ActionPhase.cpp.i
.PHONY : source/SpaceInvaders/Scenes/ActionPhase.i

# target to preprocess a source file
source/SpaceInvaders/Scenes/ActionPhase.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/ActionPhase.cpp.i
.PHONY : source/SpaceInvaders/Scenes/ActionPhase.cpp.i

source/SpaceInvaders/Scenes/ActionPhase.s: source/SpaceInvaders/Scenes/ActionPhase.cpp.s
.PHONY : source/SpaceInvaders/Scenes/ActionPhase.s

# target to generate assembly for a file
source/SpaceInvaders/Scenes/ActionPhase.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/ActionPhase.cpp.s
.PHONY : source/SpaceInvaders/Scenes/ActionPhase.cpp.s

source/SpaceInvaders/Scenes/GameOver.o: source/SpaceInvaders/Scenes/GameOver.cpp.o
.PHONY : source/SpaceInvaders/Scenes/GameOver.o

# target to build an object file
source/SpaceInvaders/Scenes/GameOver.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/GameOver.cpp.o
.PHONY : source/SpaceInvaders/Scenes/GameOver.cpp.o

source/SpaceInvaders/Scenes/GameOver.i: source/SpaceInvaders/Scenes/GameOver.cpp.i
.PHONY : source/SpaceInvaders/Scenes/GameOver.i

# target to preprocess a source file
source/SpaceInvaders/Scenes/GameOver.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/GameOver.cpp.i
.PHONY : source/SpaceInvaders/Scenes/GameOver.cpp.i

source/SpaceInvaders/Scenes/GameOver.s: source/SpaceInvaders/Scenes/GameOver.cpp.s
.PHONY : source/SpaceInvaders/Scenes/GameOver.s

# target to generate assembly for a file
source/SpaceInvaders/Scenes/GameOver.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/GameOver.cpp.s
.PHONY : source/SpaceInvaders/Scenes/GameOver.cpp.s

source/SpaceInvaders/Scenes/Intro.o: source/SpaceInvaders/Scenes/Intro.cpp.o
.PHONY : source/SpaceInvaders/Scenes/Intro.o

# target to build an object file
source/SpaceInvaders/Scenes/Intro.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/Intro.cpp.o
.PHONY : source/SpaceInvaders/Scenes/Intro.cpp.o

source/SpaceInvaders/Scenes/Intro.i: source/SpaceInvaders/Scenes/Intro.cpp.i
.PHONY : source/SpaceInvaders/Scenes/Intro.i

# target to preprocess a source file
source/SpaceInvaders/Scenes/Intro.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/Intro.cpp.i
.PHONY : source/SpaceInvaders/Scenes/Intro.cpp.i

source/SpaceInvaders/Scenes/Intro.s: source/SpaceInvaders/Scenes/Intro.cpp.s
.PHONY : source/SpaceInvaders/Scenes/Intro.s

# target to generate assembly for a file
source/SpaceInvaders/Scenes/Intro.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/Intro.cpp.s
.PHONY : source/SpaceInvaders/Scenes/Intro.cpp.s

source/SpaceInvaders/Scenes/StageCleared.o: source/SpaceInvaders/Scenes/StageCleared.cpp.o
.PHONY : source/SpaceInvaders/Scenes/StageCleared.o

# target to build an object file
source/SpaceInvaders/Scenes/StageCleared.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/StageCleared.cpp.o
.PHONY : source/SpaceInvaders/Scenes/StageCleared.cpp.o

source/SpaceInvaders/Scenes/StageCleared.i: source/SpaceInvaders/Scenes/StageCleared.cpp.i
.PHONY : source/SpaceInvaders/Scenes/StageCleared.i

# target to preprocess a source file
source/SpaceInvaders/Scenes/StageCleared.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/StageCleared.cpp.i
.PHONY : source/SpaceInvaders/Scenes/StageCleared.cpp.i

source/SpaceInvaders/Scenes/StageCleared.s: source/SpaceInvaders/Scenes/StageCleared.cpp.s
.PHONY : source/SpaceInvaders/Scenes/StageCleared.s

# target to generate assembly for a file
source/SpaceInvaders/Scenes/StageCleared.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/Scenes/StageCleared.cpp.s
.PHONY : source/SpaceInvaders/Scenes/StageCleared.cpp.s

source/SpaceInvaders/States/ActionPhaseGameState.o: source/SpaceInvaders/States/ActionPhaseGameState.cpp.o
.PHONY : source/SpaceInvaders/States/ActionPhaseGameState.o

# target to build an object file
source/SpaceInvaders/States/ActionPhaseGameState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/ActionPhaseGameState.cpp.o
.PHONY : source/SpaceInvaders/States/ActionPhaseGameState.cpp.o

source/SpaceInvaders/States/ActionPhaseGameState.i: source/SpaceInvaders/States/ActionPhaseGameState.cpp.i
.PHONY : source/SpaceInvaders/States/ActionPhaseGameState.i

# target to preprocess a source file
source/SpaceInvaders/States/ActionPhaseGameState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/ActionPhaseGameState.cpp.i
.PHONY : source/SpaceInvaders/States/ActionPhaseGameState.cpp.i

source/SpaceInvaders/States/ActionPhaseGameState.s: source/SpaceInvaders/States/ActionPhaseGameState.cpp.s
.PHONY : source/SpaceInvaders/States/ActionPhaseGameState.s

# target to generate assembly for a file
source/SpaceInvaders/States/ActionPhaseGameState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/ActionPhaseGameState.cpp.s
.PHONY : source/SpaceInvaders/States/ActionPhaseGameState.cpp.s

source/SpaceInvaders/States/GameOverGameState.o: source/SpaceInvaders/States/GameOverGameState.cpp.o
.PHONY : source/SpaceInvaders/States/GameOverGameState.o

# target to build an object file
source/SpaceInvaders/States/GameOverGameState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/GameOverGameState.cpp.o
.PHONY : source/SpaceInvaders/States/GameOverGameState.cpp.o

source/SpaceInvaders/States/GameOverGameState.i: source/SpaceInvaders/States/GameOverGameState.cpp.i
.PHONY : source/SpaceInvaders/States/GameOverGameState.i

# target to preprocess a source file
source/SpaceInvaders/States/GameOverGameState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/GameOverGameState.cpp.i
.PHONY : source/SpaceInvaders/States/GameOverGameState.cpp.i

source/SpaceInvaders/States/GameOverGameState.s: source/SpaceInvaders/States/GameOverGameState.cpp.s
.PHONY : source/SpaceInvaders/States/GameOverGameState.s

# target to generate assembly for a file
source/SpaceInvaders/States/GameOverGameState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/GameOverGameState.cpp.s
.PHONY : source/SpaceInvaders/States/GameOverGameState.cpp.s

source/SpaceInvaders/States/IntroGameState.o: source/SpaceInvaders/States/IntroGameState.cpp.o
.PHONY : source/SpaceInvaders/States/IntroGameState.o

# target to build an object file
source/SpaceInvaders/States/IntroGameState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/IntroGameState.cpp.o
.PHONY : source/SpaceInvaders/States/IntroGameState.cpp.o

source/SpaceInvaders/States/IntroGameState.i: source/SpaceInvaders/States/IntroGameState.cpp.i
.PHONY : source/SpaceInvaders/States/IntroGameState.i

# target to preprocess a source file
source/SpaceInvaders/States/IntroGameState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/IntroGameState.cpp.i
.PHONY : source/SpaceInvaders/States/IntroGameState.cpp.i

source/SpaceInvaders/States/IntroGameState.s: source/SpaceInvaders/States/IntroGameState.cpp.s
.PHONY : source/SpaceInvaders/States/IntroGameState.s

# target to generate assembly for a file
source/SpaceInvaders/States/IntroGameState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/IntroGameState.cpp.s
.PHONY : source/SpaceInvaders/States/IntroGameState.cpp.s

source/SpaceInvaders/States/StageClearedGameState.o: source/SpaceInvaders/States/StageClearedGameState.cpp.o
.PHONY : source/SpaceInvaders/States/StageClearedGameState.o

# target to build an object file
source/SpaceInvaders/States/StageClearedGameState.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/StageClearedGameState.cpp.o
.PHONY : source/SpaceInvaders/States/StageClearedGameState.cpp.o

source/SpaceInvaders/States/StageClearedGameState.i: source/SpaceInvaders/States/StageClearedGameState.cpp.i
.PHONY : source/SpaceInvaders/States/StageClearedGameState.i

# target to preprocess a source file
source/SpaceInvaders/States/StageClearedGameState.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/StageClearedGameState.cpp.i
.PHONY : source/SpaceInvaders/States/StageClearedGameState.cpp.i

source/SpaceInvaders/States/StageClearedGameState.s: source/SpaceInvaders/States/StageClearedGameState.cpp.s
.PHONY : source/SpaceInvaders/States/StageClearedGameState.s

# target to generate assembly for a file
source/SpaceInvaders/States/StageClearedGameState.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/SpaceInvaders/States/StageClearedGameState.cpp.s
.PHONY : source/SpaceInvaders/States/StageClearedGameState.cpp.s

source/Utils/Stopwatch.o: source/Utils/Stopwatch.cpp.o
.PHONY : source/Utils/Stopwatch.o

# target to build an object file
source/Utils/Stopwatch.cpp.o:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Utils/Stopwatch.cpp.o
.PHONY : source/Utils/Stopwatch.cpp.o

source/Utils/Stopwatch.i: source/Utils/Stopwatch.cpp.i
.PHONY : source/Utils/Stopwatch.i

# target to preprocess a source file
source/Utils/Stopwatch.cpp.i:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Utils/Stopwatch.cpp.i
.PHONY : source/Utils/Stopwatch.cpp.i

source/Utils/Stopwatch.s: source/Utils/Stopwatch.cpp.s
.PHONY : source/Utils/Stopwatch.s

# target to generate assembly for a file
source/Utils/Stopwatch.cpp.s:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(MAKE) $(MAKESILENT) -f SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/build.make SpaceInvaders/code/CMakeFiles/space-invaders-game-assignment.dir/source/Utils/Stopwatch.cpp.s
.PHONY : source/Utils/Stopwatch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... space-invaders-game-assignment"
	@echo "... source/Basic/string.o"
	@echo "... source/Basic/string.i"
	@echo "... source/Basic/string.s"
	@echo "... source/Graphics/SpriteRenderer.o"
	@echo "... source/Graphics/SpriteRenderer.i"
	@echo "... source/Graphics/SpriteRenderer.s"
	@echo "... source/Graphics/TextRenderer.o"
	@echo "... source/Graphics/TextRenderer.i"
	@echo "... source/Graphics/TextRenderer.s"
	@echo "... source/Math/Vec2f.o"
	@echo "... source/Math/Vec2f.i"
	@echo "... source/Math/Vec2f.s"
	@echo "... source/Platform/Display.o"
	@echo "... source/Platform/Display.i"
	@echo "... source/Platform/Display.s"
	@echo "... source/Platform/Input.o"
	@echo "... source/Platform/Input.i"
	@echo "... source/Platform/Input.s"
	@echo "... source/SpaceInvaders.o"
	@echo "... source/SpaceInvaders.i"
	@echo "... source/SpaceInvaders.s"
	@echo "... source/SpaceInvaders/Entities/Bomb/Bomb.o"
	@echo "... source/SpaceInvaders/Entities/Bomb/Bomb.i"
	@echo "... source/SpaceInvaders/Entities/Bomb/Bomb.s"
	@echo "... source/SpaceInvaders/Entities/Invader/Invader.o"
	@echo "... source/SpaceInvaders/Entities/Invader/Invader.i"
	@echo "... source/SpaceInvaders/Entities/Invader/Invader.s"
	@echo "... source/SpaceInvaders/Entities/Invader/States/AliveState.o"
	@echo "... source/SpaceInvaders/Entities/Invader/States/AliveState.i"
	@echo "... source/SpaceInvaders/Entities/Invader/States/AliveState.s"
	@echo "... source/SpaceInvaders/Entities/Invader/States/DeadState.o"
	@echo "... source/SpaceInvaders/Entities/Invader/States/DeadState.i"
	@echo "... source/SpaceInvaders/Entities/Invader/States/DeadState.s"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.o"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.i"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/BombDelegate.s"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.o"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.i"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/InvadersFleet.s"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.o"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.i"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/HorizontalMovementState.s"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.o"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.i"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/MovementStateBase.s"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.o"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.i"
	@echo "... source/SpaceInvaders/Entities/InvadersFleet/States/VerticalMovementState.s"
	@echo "... source/SpaceInvaders/Entities/Rocket/Rocket.o"
	@echo "... source/SpaceInvaders/Entities/Rocket/Rocket.i"
	@echo "... source/SpaceInvaders/Entities/Rocket/Rocket.s"
	@echo "... source/SpaceInvaders/Entities/Ship/Ship.o"
	@echo "... source/SpaceInvaders/Entities/Ship/Ship.i"
	@echo "... source/SpaceInvaders/Entities/Ship/Ship.s"
	@echo "... source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.o"
	@echo "... source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.i"
	@echo "... source/SpaceInvaders/Entities/Ship/States/ReadyToFireShipState.s"
	@echo "... source/SpaceInvaders/Entities/Ship/States/RechargingFireState.o"
	@echo "... source/SpaceInvaders/Entities/Ship/States/RechargingFireState.i"
	@echo "... source/SpaceInvaders/Entities/Ship/States/RechargingFireState.s"
	@echo "... source/SpaceInvaders/Game.o"
	@echo "... source/SpaceInvaders/Game.i"
	@echo "... source/SpaceInvaders/Game.s"
	@echo "... source/SpaceInvaders/Scenes/ActionPhase.o"
	@echo "... source/SpaceInvaders/Scenes/ActionPhase.i"
	@echo "... source/SpaceInvaders/Scenes/ActionPhase.s"
	@echo "... source/SpaceInvaders/Scenes/GameOver.o"
	@echo "... source/SpaceInvaders/Scenes/GameOver.i"
	@echo "... source/SpaceInvaders/Scenes/GameOver.s"
	@echo "... source/SpaceInvaders/Scenes/Intro.o"
	@echo "... source/SpaceInvaders/Scenes/Intro.i"
	@echo "... source/SpaceInvaders/Scenes/Intro.s"
	@echo "... source/SpaceInvaders/Scenes/StageCleared.o"
	@echo "... source/SpaceInvaders/Scenes/StageCleared.i"
	@echo "... source/SpaceInvaders/Scenes/StageCleared.s"
	@echo "... source/SpaceInvaders/States/ActionPhaseGameState.o"
	@echo "... source/SpaceInvaders/States/ActionPhaseGameState.i"
	@echo "... source/SpaceInvaders/States/ActionPhaseGameState.s"
	@echo "... source/SpaceInvaders/States/GameOverGameState.o"
	@echo "... source/SpaceInvaders/States/GameOverGameState.i"
	@echo "... source/SpaceInvaders/States/GameOverGameState.s"
	@echo "... source/SpaceInvaders/States/IntroGameState.o"
	@echo "... source/SpaceInvaders/States/IntroGameState.i"
	@echo "... source/SpaceInvaders/States/IntroGameState.s"
	@echo "... source/SpaceInvaders/States/StageClearedGameState.o"
	@echo "... source/SpaceInvaders/States/StageClearedGameState.i"
	@echo "... source/SpaceInvaders/States/StageClearedGameState.s"
	@echo "... source/Utils/Stopwatch.o"
	@echo "... source/Utils/Stopwatch.i"
	@echo "... source/Utils/Stopwatch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/alex/gitarea/playground/space-invaders-game-assignment/emscripten_build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

